### ISSUE TITLE
GCC step give RC=12 

### ISSUE THREAD

**Issue by spoofy-zz** [mainframed/CICS_Dungeon#4]
MVS Turnkey TK5 distribution with SYSC Volume.
Kicks installed in KICKS prefix.
When JCL is submitted i have RC12 return code in COMP steps.
[out.txt](https://github.com/mainframed/CICS_Dungeon/files/13206519/out.txt)

**Comment by mainframed** [comment]
Not sure why it would die there as i don't run TK5 but I had previous issued with the GCC and PDPCLIB datasets not being catalogued.

**Comment by spoofy-zz** [comment]
That not issue there, DS's are catalogued.

**Comment by mainframed** [comment]
The issue is the codepage, you need to update the tk5 conf to use `CODEPAGE  819/1047 # Uses the 1047 ASCII/EBCDIC codepage`
